In [10]:


a = np.array([[5, 7],
       [12, 18],
       [20, 29]])


b = np.array([[2, 4],
       [8, 11],
       [33, 35]])




ranges = np.vstack((a,b))

ranges.sort(0)
print(ranges)
# List of non-overlapping ranges
print(ranges[1:,0])
print()
nonoverlapping = (ranges[1:,0] - ranges[:-1,1] > 1).nonzero()[0]

# Starts are 0, and all the starts not overlapped by their predecessor
starts = np.hstack(([0], nonoverlapping + 1))

# Ends are -1 and all the ends who aren't overlapped by their successor
ends = np.hstack(( nonoverlapping, [-1]))

# Result
result = np.vstack((ranges[starts, 0], ranges[ends, 1])).T

[[ 2  4]
 [ 5  7]
 [ 8 11]
 [12 18]
 [20 29]
 [33 35]]
[ 5  8 12 20 33]

In [4]:
result

array([[ 2, 18],
       [20, 29],
       [33, 35]])

In [11]:
import json
import pandas as pd
import numpy as np

ans_df = pd.read_csv("C:\\Users\\godof\\Documents\\Data_Model_Management\\test_image_output\\20191113.csv")

In [12]:
ans_df

              filename          obj_name
0    0000_medi_014.jpg            bottle
1    0001_medi_014.jpg            bottle
2    0002_medi_014.jpg            bottle
3    0003_medi_014.jpg            bottle
4    0004_medi_014.jpg            bottle
5    0005_medi_014.jpg            bottle
6    0006_medi_014.jpg            bottle
7    0007_medi_014.jpg            bottle
8    0008_medi_014.jpg            bottle
9    0009_medi_014.jpg            bottle
10   0010_medi_014.jpg            bottle
11   0011_medi_014.jpg            bottle
12   0012_medi_014.jpg            bottle
13   0013_medi_014.jpg            bottle
14   0014_medi_014.jpg            bottle
15   0015_medi_014.jpg            bottle
16   0016_medi_014.jpg            bottle
17   0017_medi_014.jpg            bottle
18   0018_medi_014.jpg            bottle
19   0019_medi_014.jpg            bottle
20   0020_medi_014.jpg            bottle
21   0021_medi_014.jpg            bottle
22   0022_medi_014.jpg            bottle
23   0023_medi_014.jpg            bottle
24   0024_medi_014.jpg  grab_bottle_hand
25   0025_medi_014.jpg  grab_bottle_hand
26   0025_medi_014.jpg            bottle
27   0026_medi_014.jpg  grab_bottle_hand
28   0026_medi_014.jpg            bottle
29   0027_medi_014.jpg  grab_bottle_hand
..                 ...               ...
770  0666_medi_014.jpg  grab_bottle_hand
771  0667_medi_014.jpg  grab_bottle_hand
772  0668_medi_014.jpg  grab_bottle_hand
773  0669_medi_014.jpg  grab_bottle_hand
774  0670_medi_014.jpg  grab_bottle_hand
775  0671_medi_014.jpg  grab_bottle_hand
776  0671_medi_014.jpg            bottle
777  0672_medi_014.jpg  grab_bottle_hand
778  0672_medi_014.jpg            bottle
779  0673_medi_014.jpg  grab_bottle_hand
780  0673_medi_014.jpg            bottle
781  0674_medi_014.jpg            bottle
782  0675_medi_014.jpg            bottle
783  0676_medi_014.jpg            bottle
784  0676_medi_014.jpg               cup
785  0677_medi_014.jpg            bottle
786  0678_medi_014.jpg            bottle
787  0679_medi_014.jpg            bottle
788  0680_medi_014.jpg              Null
789  0681_medi_014.jpg               cup
790  0682_medi_014.jpg              Null
791  0683_medi_014.jpg              Null
792  0684_medi_014.jpg              Null
793  0685_medi_014.jpg              Null
794  0686_medi_014.jpg              Null
795  0687_medi_014.jpg              Null
796  0688_medi_014.jpg              Null
797  0689_medi_014.jpg              Null
798  0690_medi_014.jpg              Null
799  0691_medi_014.jpg              Null

[800 rows x 2 columns]

In [13]:
np_ans_df = ans_df.to_numpy()

In [14]:
for i in np_ans_df:

array([['0000_medi_014.jpg', 'bottle'],
       ['0001_medi_014.jpg', 'bottle'],
       ['0002_medi_014.jpg', 'bottle'],
       ...,
       ['0689_medi_014.jpg', 'Null'],
       ['0690_medi_014.jpg', 'Null'],
       ['0691_medi_014.jpg', 'Null']], dtype=object)