In [8]:
import json
import pandas as pd
import numpy as np

'''bbox[0] = 'ymin'
   bbox[1] = 'xmin'
   bbox[2] = 'ymax'
   bbox[3] = 'xmax'
# 0: ymin, 1: xmin, 2: ymax, 3: xmax'''
'''
def class_text_to_int(row_label):
if row_label == 'hand':
return 1
elif row_label == 'grab_bottle_hand':
return 2
elif row_label == 'face':
return 3
elif row_label == 'mouth':
return 4
elif row_label == 'open_mouth':
return 5
elif row_label == 'bottle':
return 6
elif row_label == 'open_bottle':
return 7
elif row_label == 'cap':
return 8
elif row_label == 'pill':
return 9
elif row_label == 'cup':
return 10
else:
None
'''
colum_list = ['json_source', 'filename', 'width', 'height', 'obj_name', 'xmin', 'ymin', 'xmax', 'ymax', 'score', 'obj_idx']

# row_list = []

# per_file_per_object_info_list = []

df = pd.DataFrame(columns=colum_list)


with open('200824_104348_test_299737.json') as json_file:
    json_data = json.load(json_file)
    file_name_list = list(json_data)
    for filename in file_name_list:
        print(filename)
        '''파일 1개당 json 정보'''
        '''case_1: json 정보 있는 경우 _ case_2: json 정보 없는 경우'''
        file_json_info = json_data[filename]
        if not file_json_info:
                json_source = '1106_object_list.json'
                obj_name = 'Null'
                obj_idx = 'Null'
                score = 'Null'
                ymin = 'Null'
                xmin = 'Null'
                ymax = 'Null'
                xmax = 'Null'
                width = 'Null'
                height = 'Null'
                df = df.append(pd.DataFrame([['1106_object_list.json', filename+'_', width, height, obj_name, xmin, ymin, xmax, ymax, score, obj_idx]], columns=colum_list), ignore_index=True)
                print(df)
        else:
            '''파일 1개당 감지된_되어야하는_object 갯수'''
            obj_cnt_list = list(file_json_info)
            print(obj_cnt_list)
            '''per_obj_cnt 수정 필요(삭제)'''
            per_obj_cnt = len(obj_cnt_list)
            for i in obj_cnt_list:
                final_info = file_json_info[i]
                print(final_info)
                try:
                    json_source = '1106_object_list.json'
                    obj_name = final_info['name']
                    obj_idx = final_info['obj']
                    score = final_info['score']
                    ymin = final_info['bbox'][0]
                    xmin = final_info['bbox'][1]
                    ymax = final_info['bbox'][2]
                    xmax = final_info['bbox'][3]
                    width = final_info['size'][0]
                    height = final_info['size'][1]
                    df = df.append(pd.DataFrame([['1106_object_list.json', filename+'_', width, height, obj_name, xmin, ymin, xmax, ymax, score, obj_idx]], columns=colum_list), ignore_index=True)
                    print(df)
                except:
                    pass

        
        
        '''(위에서 json 정보 없는 경우에서 걸러짐) case_1: object 있는경우 // case_2: object 없는 경우'''
        
        '''json 내 obj, name, score, bbox, size'''

[]

TypeError: list indices must be integers or slices, not list

In [56]:
df['per_obj_cnt'] = np.where(df['obj_idx'] != 'Null' , '1', '0')
df['model'] = 'inhand_20191112'+'_'
df['result_per_obj_id_int'] = df.groupby(['filename','per_obj_cnt']).cumcount()+1
df['result_per_obj_id_str'] = df['result_per_obj_id_int']

'''
apply 쓰기 위해 int-> str 형 변환
'''

df['result_per_obj_id_str'] = df['result_per_obj_id_str'].apply(str)

'''
str 형태만 결합할 수 있음, int형태는 결합 안 됨
https://www.geeksforgeeks.org/create-a-new-column-in-pandas-dataframe-based-on-the-existing-columns/
(참고)
cols = list(df.columns.values)
'''

df['per_obj_pk'] = df.apply(lambda row: row.model + row.filename+ row.result_per_obj_id_str , axis=1)
df = df.reindex(columns=['json_source', 'per_obj_pk', 'model', 'filename', 'result_per_obj_id_str', 'obj_name', 'obj_idx', 'score', 'xmin', 'ymax', 'xmax', 'ymin', 'width', 'height', 'per_obj_cnt', 'result_per_obj_id_int'])

In [57]:
df

,json_source,per_obj_pk,model,filename,result_per_obj_id_str,obj_name,obj_idx,score,xmin,ymax,xmax,ymin,width,height,per_obj_cnt,result_per_obj_id_int
0,1106_object_list.json,inhand_20191112_20IHPA1A_Test_LHW_01_1.jpg_1,inhand_20191112_,20IHPA1A_Test_LHW_01_1.jpg_,1,Null,Null,Null,Null,Null,Null,Null,Null,Null,0,1
1,1106_object_list.json,inhand_20191112_20IHPA1A_Test_LHW_01_2.jpg_1,inhand_20191112_,20IHPA1A_Test_LHW_01_2.jpg_,1,grab_bottle_body,8,0.952,434.304,318.384,1151.87,9.2448,1280,720,1,1
2,1106_object_list.json,inhand_20191112_20IHPA1A_Test_LHW_01_3.jpg_1,inhand_20191112_,20IHPA1A_Test_LHW_01_3.jpg_,1,grab_bottle_body,8,0.8984,416.768,304.488,1085.31,5.09616,1280,720,1,1
3,1106_object_list.json,inhand_20191112_20IHPA1A_Test_LHW_01_4.jpg_1,inhand_20191112_,20IHPA1A_Test_LHW_01_4.jpg_,1,grab_bottle_body,8,0.8468,420.224,310.104,1064.96,10.7208,1280,720,1,1
4,1106_object_list.json,inhand_20191112_20IHPA1A_Test_LHW_01_5.jpg_1,inhand_20191112_,20IHPA1A_Test_LHW_01_5.jpg_,1,Null,Null,Null,Null,Null,Null,Null,Null,Null,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
496,1106_object_list.json,inhand_20191112_20IHPA1A_Test_LHW_01_496.jpg_1,inhand_20191112_,20IHPA1A_Test_LHW_01_496.jpg_,1,Null,Null,Null,Null,Null,Null,Null,Null,Null,0,1
497,1106_object_list.json,inhand_20191112_20IHPA1A_Test_LHW_01_497.jpg_1,inhand_20191112_,20IHPA1A_Test_LHW_01_497.jpg_,1,Null,Null,Null,Null,Null,Null,Null,Null,Null,0,1
498,1106_object_list.json,inhand_20191112_20IHPA1A_Test_LHW_01_498.jpg_1,inhand_20191112_,20IHPA1A_Test_LHW_01_498.jpg_,1,Null,Null,Null,Null,Null,Null,Null,Null,Null,0,1
499,1106_object_list.json,inhand_20191112_20IHPA1A_Test_LHW_01_499.jpg_1,inhand_20191112_,20IHPA1A_Test_LHW_01_499.jpg_,1,Null,Null,Null,Null,Null,Null,Null,Null,Null,0,1
500,1106_object_list.json,inhand_20191112_20IHPA1A_Test_LHW_01_500.jpg_1,inhand_20191112_,20IHPA1A_Test_LHW_01_500.jpg_,1,Null,Null,Null,Null,Null,Null,Null,Null,Null,0,1

In [58]:
df.to_csv('C:\\Users\\godof\\Desktop\\original.csv',encoding='utf-8')

In [5]:
def countLetters(word):
    counter = {}
    for letter in word:
        if letter not in counter:
            counter[letter] = 0
        counter[letter] += 1
    return counter

In [47]:
t = countLetters(['cap', 'cap', 'cup'])

In [48]:
k = countLetters(['bottle', 'cap', 'cup'])

In [50]:
Counter(t) + Counter(k)

Counter({'cap': 3, 'cup': 2, 'bottle': 1})

In [39]:
orig = {
   'cap': 1,
   'cup': 2,
   'bottle': 3,
}

extra = {
   'cap': 1,
   'cup': 2,
}

In [40]:
dest = {**orig, **extra}

In [41]:
dest

{'cap': 1, 'cup': 2, 'bottle': 3}

In [42]:
from collections import Counter
a = Counter({'cap': 1, 'cup': 2})
b = Counter({'botle': 1, 'cup': 2})

In [43]:
c = a+b

In [44]:
c

Counter({'cap': 1, 'cup': 4, 'botle': 1})